spring.application.name=QL_voucher_be
# C?u hình k?t n?i Database
spring.datasource.url=jdbc:mysql://localhost:3306/test_1
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# C?u hình Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true



# C?u hình th?i gian (?? kh?p v?i ki?u DATETIME trong SQL)
spring.jackson.time-zone=Asia/Ho_Chi_Minh
